version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB:  ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    command: >
      sh -c "
              ./wait-for-it.sh db -- poetry run python deposit/manage.py migrate &&
              poetry run python deposit/manage.py runserver 0.0.0.0:8000
            "
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=deposit.settings

volumes:
  postgres_data:
